# Generated by Django 4.0.2 on 2022-02-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_client_fullname_client_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='productdescription',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='number_of_items',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='no_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('WD', 'Windsor'), ('TO', 'Toronto'), ('CH', 'Chatham'), ('WL', 'Waterloo')], default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_clients', to='myapp1.client'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='myapp1.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('0', 'cancelled'), ('1', 'placed'), ('2', 'shipped'), ('3', 'delivered')], default='0', max_length=2),
        ),
    ]
