# Generated by Django 4.0.2 on 2022-03-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_item_interested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='no_of_items',
            new_name='items_ordered',
        ),
    ]
